linux_docker_builder:
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[0082f855a406b099f9abad1fb89889f54b837633a29fcb0b91810a57b0aef7f0689cb03c5e54eb3828d6393f0a302021]
    DOCKERHUB_PASS: ENCRYPTED[b649ccee942bd1b76b20bb95252913db865325f6e8c8ef839cc7f2df040459795f0fae7fc2b1e3f3b3fe9153e08572c6]
  script: |
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

