linux_docker_builder:
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[fbeb691ae843c3dc1d5ef5a882ad4be525d4dd425ac4d43322783ac27d6c898a0acd4678f11377fc31ee22cdeb432ec1]
    DOCKERHUB_PASS: ENCRYPTED[b649ccee942bd1b76b20bb95252913db865325f6e8c8ef839cc7f2df040459795f0fae7fc2b1e3f3b3fe9153e08572c6]
  script: |
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

