linux_docker_builder:
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[fbeb691ae843c3dc1d5ef5a882ad4be525d4dd425ac4d43322783ac27d6c898a0acd4678f11377fc31ee22cdeb432ec1]
    DOCKERHUB_PASS: ENCRYPTED[!772b812133ab4de09f3e1b992941db94c7b3316617cb6c9cdae66fda4cc000076c4bc7cc87a1d7282b9677c6db53d9c9!]
  script: |
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

