linux_docker_builder:
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[fbeb691ae843c3dc1d5ef5a882ad4be525d4dd425ac4d43322783ac27d6c898a0acd4678f11377fc31ee22cdeb432ec1]
    DOCKERHUB_PASS: ENCRYPTED[2f79c2ed577df675800c976bb291f9714489a02faa8d90eb0f93ebea3de5e78335d17da7c1e3fecdb018171188b975be]
  script: |
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} . 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}

